import pandas as pd 
df = pd.read_csv(r"C:\Users\jjash\OneDrive\Desktop\ccognifyz_Datascience_internship\Dataset.csv")
print(df.head())
print("\nDataset shape:")
print(df.shape)
print("\ncolumns:")
print(df.columns)
print("\nData types:")
print(df.dtypes)
print("\nMissing values:")
print(df.isnull().sum())
print("\nDataset Info:")
df.info()
print("\nMissing values in Each Column:")
print(df.isnull().sum())
import matplotlib.pyplot as plt
plt.figure(figsize=(8,5))
df["Aggregate rating"].hist(bins=20)
plt.title("Distribution of Aggregate Ratings")
plt.xlabel("Aggregate Rating")
plt.ylabel("number of restaurants")
plt.show()
print(df["Aggregate rating"].value_counts().sort_index())
